/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_displayHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorld
 * Method:    unmapMemory
 * Signature: (Ljava/lang/Long;)V
 */
//JNIEXPORT void JNICALL Java_HelloWorld_unmapMemory
 // (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
